---
desktop_utilities:
    - brasero
    - deja-dup
    - evince
    - gnome-calculator
    - gnome-disk-utility
    - gnome-screenshot
    - gparted
    - simple-scan
accessories:
    - keepassxc
    - gedit
    - meld
    - vim
    - curl
clients:
    - firefox
    - filezilla
    - thunderbird
games:
    - pcsxr
graphics:
    - eog
    - gimp
    - pinta
bash:
    - bash-completion
    - neofetch
    - tree
sys:
    - dnsutils
    - git
    - htop
    - lsof
    - net-tools
    - openssh-client
    - rsync
    - smbclient
    - tcpdump
    - terminator
    - usbutils
    - whois
