---
themes:
    - mate-icon-theme-faenza
    - faenza-icon-theme
    - gnome-wise-icon-theme
desktop_utilities:
    - audacity
    - brasero
    - bleachbit
    - deja-dup
    - evince
    - gnome-calculator
    - gnome-disk-utility
    - gnome-screenshot
    - gparted
    - simple-scan
    - psensor
    - vlc
accessories:
    - keepassxc
    - gedit
    - gimp
    - meld
    - vim
    - curl
clients:
    - firefox-esr
    - filezilla
    - thunderbird
games:
    - pcsxr
graphics:
    - eog
    - gimp
bash:
    - bash-completion
    - neofetch
    - tree
sys:
    - curl
    - dnsutils
    - git
    - htop
    - iputils-ping
    - lsof
    - net-tools
    - openssh-client
    - rsync
    - smbclient
    - tcpdump
    - terminator
    - usbutils
    - whois
    - wget
dev:
    - code
