---
grub:
    - grub
    - grub-customizer
    - os-prober
drivers:
    - hplip
    - xf86-video-nouveau
    - xf86-video-vesa
display_manager:
    - lightdm
desktop_env:
    - cinnamon
    - nemo
    - nemo-fileroller
    - nemo-share
themes:
    - mint-themes
    - mint-x-icons
desktop_utilities:
    - brasero
    - bluez
    - blueman
    - deja-dup
    - evince
    - gnome-calculator
    - gnome-disk-utility
    - gnome-screenshot
    - gnome-keyring
    - gparted
    - libreoffice-fresh
accessories:
    - keepassxc
    - gedit
    - vim
    - bind-tools
    - curl
clients:
    - firefox
    - filezilla
    - thunderbird
    - transmission-gtk
games:
    - pcsxr
file_system:
    - cifs-utils
    - libmtp
    - gvfs-smb
    - gvfs-mtp
    - mtpfs
    - nfs-utils
    - ntfs-3g
    - samba
graphics:
    - eog
    - gimp
    - pinta
bash:
    - bash-completion
    - neofetch
    - tree
sys:
    - dialog
    - git
    - keychain
    - htop
    - iptables
    - lsof
    - linux-lts
    - meld
    - net-tools
    - netctl
    - openssh
    - rsync
    - simple-scan
    - smbclient
    - tcpdump
    - terminator
    - usbutils
    - whois
