---
- name: Install packages
  pacman: name={{ item }} state=present
  with_items:
    - ['{{ grub }}']
    - ['{{ kernel }}']
    - ['{{ drivers }}']
    - ['{{ lib }}']
    - ['{{ display_manager }}']
    - ['{{ desktop_env }}']
    - ['{{ themes }}']
    - ['{{ desktop_utilities }}']
    - ['{{ accessories }}']
    - ['{{ clients }}']
    - ['{{ games }}']
    - ['{{ file_system }}']
    - ['{{ graphics }}']
    - ['{{ bash }}']
    - ['{{ sys }}']
    - ['{{ dev }}']
    - ['{{ video }}']
    - ['{{ astronomy }}']
