---
- name: Install packages
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - "{{ themes }}" 
    - "{{ desktop_utilities }}" 
    - "{{ accessories }}" 
    - "{{ clients }}" 
    - "{{ games }}" 
    - "{{ bash }}" 
    - "{{ sys }}" 
    - "{{ dev }}" 
