---
- name: Install packages
  pacman: "{{ item }}"
  with_items:
    - "{{ desktop_env }}" 
    - "{{ themes }}" 
    - "{{ desktop_utilities }}" 
    - "{{ accessories }}" 
    - "{{ clients }}" 
    - "{{ games }}" 
    - "{{ bash }}" 
    - "{{ sys }}" 
