---
- hosts: localhost
  connection: local
  become: yes
  become_user: root
  roles:
   - iptables
  # Archlinux
   - { role: "paru", when: (ansible_distribution == 'Archlinux') }
   - { role: "rsyslog", when: (ansible_distribution == 'Archlinux') }
   - { role: "services", when: (ansible_distribution == 'Archlinux') }
   - { role: "pacman", when: (ansible_distribution == 'Archlinux') }
  # Debian
   - { role: "apt", when: (ansible_distribution == 'Debian') }
